(part "TGS2620"
    (packageRef "TGS2620")
    (interface
        (port "1" (symbPinId 1) (portName "HEATER_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SENSOR_ELECTRODE_(-)") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SENSOR_ELECTRODE_(+)") (portType INOUT))
        (port "4" (symbPinId 4) (portName "HEATER_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Figaro")
    (property "Manufacturer_Part_Number" "TGS2620")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Figaro TGS2620 Alcohol, Solvent Vapors Gas Sensor")
    (property "Datasheet_Link" "https://docs-emea.rs-online.com/webdocs/065f/0900766b8065f2e8.pdf")
    (property "symbolName1" "TGS2620")
)
